/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tree.java
 *
 * Created on 15 Nov, 2012, 5:00:42 PM
 */
package Fractals;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;

/**
 *
 * @author Rakshak.R.Hegde
 */
public class TreeFractal extends javax.swing.JFrame {

    boolean colorWhite = true;

    public TreeFractal() {
        initComponents();
        ((Painter) painter).initialize();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painter = new Painter();
        colorButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tree Fractal");
        setResizable(false);

        colorButton.setText("Toggle Color");
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painterLayout = new javax.swing.GroupLayout(painter);
        painter.setLayout(painterLayout);
        painterLayout.setHorizontalGroup(
            painterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorButton)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        painterLayout.setVerticalGroup(
            painterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
    colorWhite = !colorWhite;
    repaint();
}//GEN-LAST:event_colorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TreeFractal();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton colorButton;
    private JPanel painter;
    // End of variables declaration//GEN-END:variables

    class Painter extends JPanel {

        BufferedImage image;
        Graphics2D g2d;
        int width, height;
        float length = 200, angle, mouseX, mouseY;
        float shrinkLength = 0.6f;
        GradientPaint gradient1, gradient2;

        public void initialize() {
            width = getWidth();
            height = getHeight();
            gradient1 = new GradientPaint(0, 0, Color.black, 0, height, new Color(100, 100, 100));
            gradient2 = new GradientPaint(0, 0, Color.white, 0, height, Color.LIGHT_GRAY);
            addMouseMotionListener(new MouseMotionAdapter() {

                @Override
                public void mouseMoved(MouseEvent e) {
                    super.mouseMoved(e);
                    mouseX = e.getX();
                    mouseY = e.getY();
                    repaint();
                }
            });

            image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            g2d = image.createGraphics();
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2d.setStroke(new BasicStroke(2, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));
        }

        public void render(float length, double angle, int step) {
            if (step-- > 0) {
                g2d.rotate(angle);
                g2d.drawLine(0, 0, 0, (int) -length);
                g2d.translate(0, -length);
                render(length * shrinkLength, -angle, step);
                render(length * shrinkLength, angle, step);
                g2d.translate(0, length);
                g2d.rotate(-angle);
            }
        }

        public void paintComponent(Graphics g) {
            super.paintComponent(g);

            if (colorWhite) {
                g2d.setPaint(gradient2);
                g2d.fillRect(0, 0, width, height);
                g2d.setColor(Color.black);
            } else {
                g2d.setPaint(gradient1);
                g2d.fillRect(0, 0, width, height);
                g2d.setColor(Color.white);
            }
            angle = (float) (mouseX / width * Math.PI / 2);
            g2d.translate(width / 2f, height);
            g2d.rotate(-angle);
            render(length, angle, (int) (mouseY / height * 9f + 1));
            g2d.rotate(angle);
            g2d.translate(-width / 2f, -height);

            g.drawImage(image, (getWidth()-image.getWidth())/2, (getHeight()-image.getHeight())/2, null);
        }
    }
}
