/*
 * Created on 9 Nov, 2012, 8:23:33 PM
 */
package Miscellaneous;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.UIManager;

/**
 * @author Rakshak.R.Hegde
 */
public class ColorChooser extends javax.swing.JFrame {

    Clipboard clipboard;
    Color color;
    int r, g, b, a;
    float hsbVal[] = new float[3];

    public ColorChooser() {
        initComponents();
        clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        colorChooser = new javax.swing.JColorChooser();
        hslButton = new javax.swing.JButton();
        rgbButton = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Color Chooser");
        setBackground(new Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Color Chooser"));

        colorChooser.setBackground(new Color(255, 255, 255));
        colorChooser.setOpaque(false);

        hslButton.setText("Copy HSL");
        hslButton.setToolTipText("Copies the Hue, Saturation & Lightness values of the color chosen to the clipboard");
        hslButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hslButtonActionPerformed(evt);
            }
        });

        rgbButton.setText("Copy RGB");
        rgbButton.setToolTipText("Copies the Red, Green & Blue values of the color chosen to the clipboard");
        rgbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgbButtonActionPerformed(evt);
            }
        });

        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "As single int", "As four int" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(colorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rgbButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(hslButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(hslButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(rgbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void hslButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hslButtonActionPerformed
    color = colorChooser.getColor();
    r = color.getRed();
    g = color.getGreen();
    b = color.getBlue();
    Color.RGBtoHSB(r, g, b, hsbVal);
    clipboard.setContents(new StringSelection(hsbVal[0] + ", " + hsbVal[1] + ", " + hsbVal[2]), null);
}//GEN-LAST:event_hslButtonActionPerformed

private void rgbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgbButtonActionPerformed
    color = colorChooser.getColor();
    if (comboBox.getSelectedIndex() == 0) {
        clipboard.setContents(new StringSelection(color.getRGB() + ""), null);
    } else {
        r = color.getRed();
        g = color.getGreen();
        b = color.getBlue();
        a = color.getAlpha();
        clipboard.setContents(new StringSelection(r + ", " + g + ", " + b + ", " + a), null);
    }
}//GEN-LAST:event_rgbButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ColorChooser();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JButton hslButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rgbButton;
    // End of variables declaration//GEN-END:variables
}
